// Ronda 77, a pedido explícito del usuario: catálogo de nacionalidades
// (mismo patrón que la tabla "profesion" de la ronda 74) para que el nuevo
// campo "nacionalidad" del residente ya no sea texto libre — se elige de
// una lista (combobox autocompletable, ver AdminResidentesScreen y
// GET /nacionalidades).
//
// El campo "codigo" es un correlativo INTERNO de esta tabla (001, 002...),
// no un código ISO ni de ningún organismo oficial — igual que en
// "profesion", es solo para tener una clave estable y ordenable.
//
// Los nombres de países están en español y cubren los ~197 países
// reconocidos, organizados originalmente por continente al generarlos
// (América, Europa, Asia, Oceanía, África) pero el listado del combobox
// en la app se ordena alfabéticamente en la consulta (ORDER BY
// gls_nacionalidad), no por este orden de inserción.
exports.up = async function (knex) {
  await knex.schema.createTable("nacionalidad", (table) => {
    table.increments("id_nacionalidad").primary();
    table.string("codigo", 10).notNullable().unique();
    table.string("gls_nacionalidad", 150).notNullable().unique();
    table.integer("flg_vigencia").notNullable().defaultTo(1);
  });

  await knex("nacionalidad").insert([
  { codigo: "001", gls_nacionalidad: 'Chile' },
  { codigo: "002", gls_nacionalidad: 'Argentina' },
  { codigo: "003", gls_nacionalidad: 'Perú' },
  { codigo: "004", gls_nacionalidad: 'Bolivia' },
  { codigo: "005", gls_nacionalidad: 'Colombia' },
  { codigo: "006", gls_nacionalidad: 'Ecuador' },
  { codigo: "007", gls_nacionalidad: 'Venezuela' },
  { codigo: "008", gls_nacionalidad: 'Paraguay' },
  { codigo: "009", gls_nacionalidad: 'Uruguay' },
  { codigo: "010", gls_nacionalidad: 'Brasil' },
  { codigo: "011", gls_nacionalidad: 'México' },
  { codigo: "012", gls_nacionalidad: 'Estados Unidos' },
  { codigo: "013", gls_nacionalidad: 'Canadá' },
  { codigo: "014", gls_nacionalidad: 'Cuba' },
  { codigo: "015", gls_nacionalidad: 'República Dominicana' },
  { codigo: "016", gls_nacionalidad: 'Haití' },
  { codigo: "017", gls_nacionalidad: 'Jamaica' },
  { codigo: "018", gls_nacionalidad: 'Bahamas' },
  { codigo: "019", gls_nacionalidad: 'Trinidad y Tobago' },
  { codigo: "020", gls_nacionalidad: 'Barbados' },
  { codigo: "021", gls_nacionalidad: 'Granada' },
  { codigo: "022", gls_nacionalidad: 'San Vicente y las Granadinas' },
  { codigo: "023", gls_nacionalidad: 'Santa Lucía' },
  { codigo: "024", gls_nacionalidad: 'Dominica' },
  { codigo: "025", gls_nacionalidad: 'Antigua y Barbuda' },
  { codigo: "026", gls_nacionalidad: 'San Cristóbal y Nieves' },
  { codigo: "027", gls_nacionalidad: 'Belice' },
  { codigo: "028", gls_nacionalidad: 'Guatemala' },
  { codigo: "029", gls_nacionalidad: 'Honduras' },
  { codigo: "030", gls_nacionalidad: 'El Salvador' },
  { codigo: "031", gls_nacionalidad: 'Nicaragua' },
  { codigo: "032", gls_nacionalidad: 'Costa Rica' },
  { codigo: "033", gls_nacionalidad: 'Panamá' },
  { codigo: "034", gls_nacionalidad: 'Guyana' },
  { codigo: "035", gls_nacionalidad: 'Surinam' },
  { codigo: "036", gls_nacionalidad: 'España' },
  { codigo: "037", gls_nacionalidad: 'Francia' },
  { codigo: "038", gls_nacionalidad: 'Alemania' },
  { codigo: "039", gls_nacionalidad: 'Italia' },
  { codigo: "040", gls_nacionalidad: 'Reino Unido' },
  { codigo: "041", gls_nacionalidad: 'Portugal' },
  { codigo: "042", gls_nacionalidad: 'Países Bajos' },
  { codigo: "043", gls_nacionalidad: 'Bélgica' },
  { codigo: "044", gls_nacionalidad: 'Suiza' },
  { codigo: "045", gls_nacionalidad: 'Austria' },
  { codigo: "046", gls_nacionalidad: 'Irlanda' },
  { codigo: "047", gls_nacionalidad: 'Suecia' },
  { codigo: "048", gls_nacionalidad: 'Noruega' },
  { codigo: "049", gls_nacionalidad: 'Dinamarca' },
  { codigo: "050", gls_nacionalidad: 'Finlandia' },
  { codigo: "051", gls_nacionalidad: 'Islandia' },
  { codigo: "052", gls_nacionalidad: 'Polonia' },
  { codigo: "053", gls_nacionalidad: 'República Checa' },
  { codigo: "054", gls_nacionalidad: 'Eslovaquia' },
  { codigo: "055", gls_nacionalidad: 'Hungría' },
  { codigo: "056", gls_nacionalidad: 'Rumania' },
  { codigo: "057", gls_nacionalidad: 'Bulgaria' },
  { codigo: "058", gls_nacionalidad: 'Grecia' },
  { codigo: "059", gls_nacionalidad: 'Croacia' },
  { codigo: "060", gls_nacionalidad: 'Eslovenia' },
  { codigo: "061", gls_nacionalidad: 'Serbia' },
  { codigo: "062", gls_nacionalidad: 'Bosnia y Herzegovina' },
  { codigo: "063", gls_nacionalidad: 'Montenegro' },
  { codigo: "064", gls_nacionalidad: 'Macedonia del Norte' },
  { codigo: "065", gls_nacionalidad: 'Albania' },
  { codigo: "066", gls_nacionalidad: 'Kosovo' },
  { codigo: "067", gls_nacionalidad: 'Moldavia' },
  { codigo: "068", gls_nacionalidad: 'Ucrania' },
  { codigo: "069", gls_nacionalidad: 'Rusia' },
  { codigo: "070", gls_nacionalidad: 'Bielorrusia' },
  { codigo: "071", gls_nacionalidad: 'Lituania' },
  { codigo: "072", gls_nacionalidad: 'Letonia' },
  { codigo: "073", gls_nacionalidad: 'Estonia' },
  { codigo: "074", gls_nacionalidad: 'Luxemburgo' },
  { codigo: "075", gls_nacionalidad: 'Malta' },
  { codigo: "076", gls_nacionalidad: 'Chipre' },
  { codigo: "077", gls_nacionalidad: 'Mónaco' },
  { codigo: "078", gls_nacionalidad: 'Liechtenstein' },
  { codigo: "079", gls_nacionalidad: 'Andorra' },
  { codigo: "080", gls_nacionalidad: 'San Marino' },
  { codigo: "081", gls_nacionalidad: 'Vaticano' },
  { codigo: "082", gls_nacionalidad: 'China' },
  { codigo: "083", gls_nacionalidad: 'Japón' },
  { codigo: "084", gls_nacionalidad: 'Corea del Sur' },
  { codigo: "085", gls_nacionalidad: 'Corea del Norte' },
  { codigo: "086", gls_nacionalidad: 'India' },
  { codigo: "087", gls_nacionalidad: 'Pakistán' },
  { codigo: "088", gls_nacionalidad: 'Bangladés' },
  { codigo: "089", gls_nacionalidad: 'Sri Lanka' },
  { codigo: "090", gls_nacionalidad: 'Nepal' },
  { codigo: "091", gls_nacionalidad: 'Bután' },
  { codigo: "092", gls_nacionalidad: 'Maldivas' },
  { codigo: "093", gls_nacionalidad: 'Afganistán' },
  { codigo: "094", gls_nacionalidad: 'Irán' },
  { codigo: "095", gls_nacionalidad: 'Irak' },
  { codigo: "096", gls_nacionalidad: 'Arabia Saudita' },
  { codigo: "097", gls_nacionalidad: 'Emiratos Árabes Unidos' },
  { codigo: "098", gls_nacionalidad: 'Catar' },
  { codigo: "099", gls_nacionalidad: 'Kuwait' },
  { codigo: "100", gls_nacionalidad: 'Baréin' },
  { codigo: "101", gls_nacionalidad: 'Omán' },
  { codigo: "102", gls_nacionalidad: 'Yemen' },
  { codigo: "103", gls_nacionalidad: 'Jordania' },
  { codigo: "104", gls_nacionalidad: 'Líbano' },
  { codigo: "105", gls_nacionalidad: 'Siria' },
  { codigo: "106", gls_nacionalidad: 'Israel' },
  { codigo: "107", gls_nacionalidad: 'Palestina' },
  { codigo: "108", gls_nacionalidad: 'Turquía' },
  { codigo: "109", gls_nacionalidad: 'Georgia' },
  { codigo: "110", gls_nacionalidad: 'Armenia' },
  { codigo: "111", gls_nacionalidad: 'Azerbaiyán' },
  { codigo: "112", gls_nacionalidad: 'Kazajistán' },
  { codigo: "113", gls_nacionalidad: 'Uzbekistán' },
  { codigo: "114", gls_nacionalidad: 'Turkmenistán' },
  { codigo: "115", gls_nacionalidad: 'Kirguistán' },
  { codigo: "116", gls_nacionalidad: 'Tayikistán' },
  { codigo: "117", gls_nacionalidad: 'Mongolia' },
  { codigo: "118", gls_nacionalidad: 'Taiwán' },
  { codigo: "119", gls_nacionalidad: 'Vietnam' },
  { codigo: "120", gls_nacionalidad: 'Laos' },
  { codigo: "121", gls_nacionalidad: 'Camboya' },
  { codigo: "122", gls_nacionalidad: 'Tailandia' },
  { codigo: "123", gls_nacionalidad: 'Myanmar' },
  { codigo: "124", gls_nacionalidad: 'Malasia' },
  { codigo: "125", gls_nacionalidad: 'Singapur' },
  { codigo: "126", gls_nacionalidad: 'Indonesia' },
  { codigo: "127", gls_nacionalidad: 'Filipinas' },
  { codigo: "128", gls_nacionalidad: 'Brunéi' },
  { codigo: "129", gls_nacionalidad: 'Timor Oriental' },
  { codigo: "130", gls_nacionalidad: 'Australia' },
  { codigo: "131", gls_nacionalidad: 'Nueva Zelanda' },
  { codigo: "132", gls_nacionalidad: 'Papúa Nueva Guinea' },
  { codigo: "133", gls_nacionalidad: 'Fiyi' },
  { codigo: "134", gls_nacionalidad: 'Islas Salomón' },
  { codigo: "135", gls_nacionalidad: 'Vanuatu' },
  { codigo: "136", gls_nacionalidad: 'Samoa' },
  { codigo: "137", gls_nacionalidad: 'Tonga' },
  { codigo: "138", gls_nacionalidad: 'Kiribati' },
  { codigo: "139", gls_nacionalidad: 'Micronesia' },
  { codigo: "140", gls_nacionalidad: 'Palaos' },
  { codigo: "141", gls_nacionalidad: 'Islas Marshall' },
  { codigo: "142", gls_nacionalidad: 'Nauru' },
  { codigo: "143", gls_nacionalidad: 'Tuvalu' },
  { codigo: "144", gls_nacionalidad: 'Egipto' },
  { codigo: "145", gls_nacionalidad: 'Libia' },
  { codigo: "146", gls_nacionalidad: 'Túnez' },
  { codigo: "147", gls_nacionalidad: 'Argelia' },
  { codigo: "148", gls_nacionalidad: 'Marruecos' },
  { codigo: "149", gls_nacionalidad: 'Mauritania' },
  { codigo: "150", gls_nacionalidad: 'Malí' },
  { codigo: "151", gls_nacionalidad: 'Níger' },
  { codigo: "152", gls_nacionalidad: 'Chad' },
  { codigo: "153", gls_nacionalidad: 'Sudán' },
  { codigo: "154", gls_nacionalidad: 'Sudán del Sur' },
  { codigo: "155", gls_nacionalidad: 'Etiopía' },
  { codigo: "156", gls_nacionalidad: 'Eritrea' },
  { codigo: "157", gls_nacionalidad: 'Yibuti' },
  { codigo: "158", gls_nacionalidad: 'Somalia' },
  { codigo: "159", gls_nacionalidad: 'Kenia' },
  { codigo: "160", gls_nacionalidad: 'Uganda' },
  { codigo: "161", gls_nacionalidad: 'Tanzania' },
  { codigo: "162", gls_nacionalidad: 'Ruanda' },
  { codigo: "163", gls_nacionalidad: 'Burundi' },
  { codigo: "164", gls_nacionalidad: 'República Democrática del Congo' },
  { codigo: "165", gls_nacionalidad: 'República del Congo' },
  { codigo: "166", gls_nacionalidad: 'Gabón' },
  { codigo: "167", gls_nacionalidad: 'Guinea Ecuatorial' },
  { codigo: "168", gls_nacionalidad: 'Camerún' },
  { codigo: "169", gls_nacionalidad: 'República Centroafricana' },
  { codigo: "170", gls_nacionalidad: 'Nigeria' },
  { codigo: "171", gls_nacionalidad: 'Benín' },
  { codigo: "172", gls_nacionalidad: 'Togo' },
  { codigo: "173", gls_nacionalidad: 'Ghana' },
  { codigo: "174", gls_nacionalidad: 'Costa de Marfil' },
  { codigo: "175", gls_nacionalidad: 'Liberia' },
  { codigo: "176", gls_nacionalidad: 'Sierra Leona' },
  { codigo: "177", gls_nacionalidad: 'Guinea' },
  { codigo: "178", gls_nacionalidad: 'Guinea-Bisáu' },
  { codigo: "179", gls_nacionalidad: 'Senegal' },
  { codigo: "180", gls_nacionalidad: 'Gambia' },
  { codigo: "181", gls_nacionalidad: 'Cabo Verde' },
  { codigo: "182", gls_nacionalidad: 'Santo Tomé y Príncipe' },
  { codigo: "183", gls_nacionalidad: 'Angola' },
  { codigo: "184", gls_nacionalidad: 'Zambia' },
  { codigo: "185", gls_nacionalidad: 'Malaui' },
  { codigo: "186", gls_nacionalidad: 'Mozambique' },
  { codigo: "187", gls_nacionalidad: 'Zimbabue' },
  { codigo: "188", gls_nacionalidad: 'Botsuana' },
  { codigo: "189", gls_nacionalidad: 'Namibia' },
  { codigo: "190", gls_nacionalidad: 'Sudáfrica' },
  { codigo: "191", gls_nacionalidad: 'Lesoto' },
  { codigo: "192", gls_nacionalidad: 'Esuatini' },
  { codigo: "193", gls_nacionalidad: 'Madagascar' },
  { codigo: "194", gls_nacionalidad: 'Mauricio' },
  { codigo: "195", gls_nacionalidad: 'Seychelles' },
  { codigo: "196", gls_nacionalidad: 'Comoras' },
  { codigo: "197", gls_nacionalidad: 'Burkina Faso' },
  ]);
};

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists("nacionalidad");
};
